import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    user_id: 'mock-user-id',
    name: 'Fone de Ouvido Sony WH-1000XM5 com Cancelamento de Ruído',
    description: 'Cancelamento de ruído líder da indústria otimizado para você. Som magnífico, projetado para a perfeição.',
    price: 1740.00,
    currency: 'BRL',
    image_url: 'https://picsum.photos/400/400?random=1',
    affiliate_link: '#',
    affiliate_platform: 'Amazon',
    category: 'Eletrônicos',
    tags: 'sony,audio,headphones',
    slug: 'sony-wh-1000xm5',
    meta_description: 'Best noise cancelling headphones',
    rating: 4.8,
    review_count: 2304,
    is_featured: true,
    is_active: true,
    created_at: '2023-10-01T10:00:00Z',
    updated_at: '2023-10-01T10:00:00Z',
    click_count: 1250,
    view_count: 5000
  },
  {
    id: '2',
    user_id: 'mock-user-id',
    name: 'MacBook Air M2 13 polegadas',
    description: 'Superpotente com o chip M2 de próxima geração, o MacBook Air redesenhado combina desempenho incrível com até 18 horas de bateria.',
    price: 5499.00,
    currency: 'BRL',
    image_url: 'https://picsum.photos/400/400?random=2',
    affiliate_link: '#',
    affiliate_platform: 'Amazon',
    category: 'Notebooks',
    tags: 'apple,macbook,laptop',
    slug: 'macbook-air-m2',
    meta_description: 'Apple M2 Laptop',
    rating: 4.9,
    review_count: 850,
    is_featured: true,
    is_active: true,
    created_at: '2023-10-05T10:00:00Z',
    updated_at: '2023-10-05T10:00:00Z',
    click_count: 3400,
    view_count: 10000
  },
  {
    id: '3',
    user_id: 'mock-user-id',
    name: 'Logitech MX Master 3S',
    description: 'Um ícone remasterizado. Sinta cada momento do seu fluxo de trabalho com ainda mais precisão, tatilidade e desempenho.',
    price: 499.99,
    currency: 'BRL',
    image_url: 'https://picsum.photos/400/400?random=3',
    affiliate_link: '#',
    affiliate_platform: 'Amazon',
    category: 'Acessórios',
    tags: 'logitech,mouse,productivity',
    slug: 'logitech-mx-master-3s',
    meta_description: 'Best mouse for productivity',
    rating: 4.7,
    review_count: 5420,
    is_featured: false,
    is_active: true,
    created_at: '2023-09-15T10:00:00Z',
    updated_at: '2023-09-15T10:00:00Z',
    click_count: 890,
    view_count: 2000
  },
  {
    id: '4',
    user_id: 'mock-user-id',
    name: 'Curso React Avançado 2024',
    description: 'Domine o ecossistema React, padrões e otimização de desempenho com este curso completo em vídeo.',
    price: 249.90,
    currency: 'BRL',
    image_url: 'https://picsum.photos/400/400?random=4',
    affiliate_link: '#',
    affiliate_platform: 'Hotmart',
    category: 'Educação',
    tags: 'react,course,programming',
    slug: 'react-advanced-2024',
    meta_description: 'Advanced React Course',
    rating: 4.9,
    review_count: 120,
    is_featured: true,
    is_active: true,
    created_at: '2023-10-20T10:00:00Z',
    updated_at: '2023-10-20T10:00:00Z',
    click_count: 450,
    view_count: 900
  },
  {
    id: '5',
    user_id: 'mock-user-id',
    name: 'Cadeira de Escritório Ergonômica',
    description: 'Dê às suas costas o suporte que elas precisam. Suporte lombar ajustável e malha respirável.',
    price: 1250.00,
    currency: 'BRL',
    image_url: 'https://picsum.photos/400/400?random=5',
    affiliate_link: '#',
    affiliate_platform: 'Mercado Livre',
    category: 'Móveis',
    tags: 'chair,ergonomic,office',
    slug: 'ergonomic-office-chair',
    meta_description: 'Comfortable office chair',
    rating: 4.5,
    review_count: 310,
    is_featured: false,
    is_active: true,
    created_at: '2023-08-10T10:00:00Z',
    updated_at: '2023-08-10T10:00:00Z',
    click_count: 210,
    view_count: 600
  },
  {
    id: '6',
    user_id: 'mock-user-id',
    name: 'Teclado Mecânico Keychron K2',
    description: 'Um teclado mecânico sem fio super tátil com layout para Mac e Windows.',
    price: 395.00,
    currency: 'BRL',
    image_url: 'https://picsum.photos/400/400?random=6',
    affiliate_link: '#',
    affiliate_platform: 'Amazon',
    category: 'Acessórios',
    tags: 'keychron,keyboard,mechanical',
    slug: 'keychron-k2',
    meta_description: 'Mechanical Wireless Keyboard',
    rating: 4.6,
    review_count: 890,
    is_featured: false,
    is_active: true,
    created_at: '2023-10-25T10:00:00Z',
    updated_at: '2023-10-25T10:00:00Z',
    click_count: 670,
    view_count: 1500
  }
];

export const CATEGORIES = ['Todos', 'Eletrônicos', 'Notebooks', 'Acessórios', 'Educação', 'Móveis'];

export const PLATFORMS = ['Amazon', 'Hotmart', 'Mercado Livre', 'Outro'];